### PR TITLE
config_tool: test ci trigger by pr

### PR DESCRIPTION
**Pull request by szhen11**
Signed-off-by: Shuang Zheng <shuang.zheng@intel.com>

### CODE REVIEW

**Review by pengfujx — APPROVED** [review]

**Comment by pengfujx** [comment]
approved these changes

**Comment by szhen11** [comment]
run tests

**Comment by szhen11** [comment]
approved these changes

**Review by pengfujx — APPROVED** [review]

**Comment by szhen11** [comment]
start to run permerge test

**Comment by szhen11** [comment]
start to run permerge test

**Comment by szhen11** [comment]
start to run permerge test

**Comment by szhen11** [comment]
start to run permerge test

**Comment by szhen11** [comment]
start to run permerge test

**Comment by szhen11** [comment]
start to run permerge test

**Comment by szhen11** [comment]
start to run permerge test

**Comment by szhen11** [comment]
start to run permerge test

**Comment by szhen11** [comment]
start to run permerge test

**Comment by szhen11** [comment]
start to run permerge test

**Comment by szhen11** [comment]
start to run permerge test

**Comment by szhen11** [comment]
start to run permerge test

**Comment by szhen11** [comment]
start to run permerge test

**Comment by szhen11** [comment]
start to run permerge test

**Comment by szhen11** [comment]
start to run permerge test

**Comment by szhen11** [comment]
start to run permerge test

**Comment by szhen11** [comment]
start to run permerge test

**Comment by szhen11** [comment]
start to run permerge test

**Comment by szhen11** [comment]
start to run permerge test

**Comment by szhen11** [comment]
start to run permerge test

**Comment by szhen11** [comment]
start to run permerge test

**Comment by szhen11** [comment]
start to run permerge test

**Comment by szhen11** [comment]
start to run permerge test

**Comment by szhen11** [comment]
start to run permerge test

**Comment by szhen11** [comment]
start to run permerge test

**Comment by szhen11** [comment]
start to run permerge test

**Comment by szhen11** [comment]
start to run permerge test

**Comment by szhen11** [comment]
start to run permerge test

**Comment by szhen11** [comment]
start to run permerge test

**Comment by szhen11** [comment]
start to run permerge test

**Comment by szhen11** [comment]
start to run permerge test

**Comment by szhen11** [comment]
start to run permerge test

**Pull request merged**
